SELECT FLAVOR
FROM (
    SELECT RANK() OVER(ORDER BY SUM(TOTAL_ORDER) DESC) AS RNK,
           FLAVOR
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF

        UNION ALL

        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
    ) A
    GROUP BY FLAVOR
) B
WHERE RNK <= 3
ORDER BY RNK;